# Setup
title:               Ati Sharma
description:         CV and publications
url:                 https://atisharma.info
baseurl:             ''
permalink:           /:categories/:title/
markdown:            kramdown
highlighter:         rouge

kramdown:
    toc_levels: 1..2

# About/contact
author:
  name:              Ati Sharma
  url:               https://atisharma.info
  email:             ati@agalmic.ltd

# Gems
plugins:
  - jekyll-redirect-from

