# Setup
title:               Ati's notes
tagline:             'Ati\'s notes'
description:         'Ati\'s notes on various topics'
url:                 https://atisharma.github.io
baseurl:             ''
#paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ati Sharma
  url:               https://atisharma.github.io
  email:             ati@agalmic.ltd

# Gems
#plugins:
  #- jekyll-paginate

# Custom vars
version:             0.0.1
#google_analytics_id: #UA-XXXX-Y
