# Setup
title:               Ati Sharma
tagline:             As simple as possible without being wrong
description:         Notes on various topics
url:                 https://atisharma.info
baseurl:             ''
permalink:           /:categories/:title/
markdown:            kramdown
highlighter:         rouge

kramdown:
    toc_levels: 1..2

# About/contact
author:
  name:              Ati Sharma
  url:               https://atisharma.info
  email:             ati@agalmic.ltd

# Gems
#plugins:

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
